#!/bin/bash

# check if running as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 0
fi

# check if -t is provided
if [[ "$1" != "-t" ]]; then
  python3 $(echo "/etc/scripts/dns_zone_helper.py A ${@}")
  exit 0
fi

# get params after -t
params=${@:2}
python3 $(echo "/etc/scripts/dns_zone_helper.py $params")

# restart bind9
systemctl restart bind9
