#!/bin/bash

if [[ "$1" != "" ]]; then
  subdomain="$1"
else
  echo "No subdomain given as first argument"
  exit 0
fi

# append subdomain to named.conf.mrt-zones
echo "" >> /etc/bind/named.conf.mrt-zones
echo "// $subdomain config"  >> /etc/bind/named.conf.mrt-zones
echo "zone $subdomain.indy-naessens.sb.uclllabs.be. {
	type master;
	file \"/etc/bind/zones/db.mrt.$subdomain.indy-naessens.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.mrt-zones

# create zonefile
echo "\$TTL	300
@	IN	SOA	ns.$subdomain.indy-naessens.sb.uclllabs.be. admin.indy-naessens.sb.uclllabs.be. (
			    001		; Serial
			    300		; Refresh
			    300		; Retry
			2419200		; Expire
			    300)	; Negative Cache TTL
; Name servers
@       IN      NS      ns.$subdomain.indy-naessens.sb.uclllabs.be.
@       IN      NS      ns.indy-naessens.sb.uclllabs.be.


; A records
@	IN	A	193.191.177.148
ns	IN	A	193.191.177.148" >> $(echo "/etc/bind/zones/db.mrt.$subdomain.indy-naessens.sb.uclllabs.be")

# delegation
echo "$subdomain       IN      NS      ns.indy-naessens.sb.uclllabs.be." >> /etc/bind/zones/db.indy-naessens.sb.uclllabs.be

# increase serial
old=$(grep "Serial" /etc/bind/zones/db.indy-naessens.sb.uclllabs.be | tr -s [:blank:] | cut -d ' ' -f 2)
new=$((old + 1))
sed -i "s/.*Serial.*/\t\t     $new ;Serial/g" /etc/bind/zones/db.indy-naessens.sb.uclllabs.be

#reload named.confs and zones
rndc reconfig
rndc reload
