#!/bin/bash

# check if running as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# check if -t is provided
if [[ "$1" != "-t" ]]; then
  echo "No -t option provided as first argument, $1 is given instead"
  exit 0
fi

# get params after -t
params=${@:2}
python3 $(echo "/etc/scripts/dns_zone_helper.py $params")

# reload zone
rndc reload
