#!/bin/bash

# Functions
start () {
  echo "Starting firewall"
}

stop () {
  iptables-restore /etc/scripts/firewall/empty_firewall_v4 -v
  ip6tables-restore /etc/scripts/firewall/empty_firewall_v6 -v
}

# Program Enty
action=$1

if [ "$action" = "start" ]; then
  start
elif [ "$action" = "stop" ]; then
  stop
elif [ "$action" = "restart"  ]; then
  stop
  start
else
  echo "Parameters: {start|stop|restart}"
fi
