#!/bin/bash

# Functions
start_iptables_rules () {
  iptables-restore /etc/scripts/firewall/rules_firewall_v4 -v
  ip6tables-restore /etc/scripts/firewall/rules_firewall_v6 -v
}

stop_iptables_rules () {
  iptables-restore /etc/scripts/firewall/empty_firewall_v4 -v
  ip6tables-restore /etc/scripts/firewall/empty_firewall_v6 -v
}

# Program Enty
action=$1

if [ "$action" = "start" ]; then
  start_iptables_rules

  # disable ip routing
  sysctl -w net.ipv4.ip_forward=0 # default

  # enable tcp syn cookies
  sysctl -w net.ipv4.tcp_syncookies=1 # default
elif [ "$action" = "stop" ]; then
  stop_iptables_rules
elif [ "$action" = "restart"  ]; then
  stop_iptables_rules
  start_iptables_rules
else
  echo "Parameters: {start|stop|restart}"
fi
